---
- hosts: web01
  vars:
    db_user: vishal
    db_name: ansible-test
  tasks:
   - name: Mysql server installation
     yum: name={{item}} state=present update_cache=yes
     with_items:
       - mariadb-server
       - MySQL-python
  
   - name: Service mysql start
     service: name=mariadb state=restarted enabled=yes

   - name: Change root user password on first run
     mysql_user:
       login_host: localhost
       login_user: root
       login_password: ''
       name: root
       password: Miami@2019
       priv: "*.*:ALL,GRANT"
       host: '%'

   - name: assigne myswl username in vairaoble
     delegate_to: localhost
     command: cat /root/file.txt
     register: new_name
   - name: show variable value
     debug:
       msg: "{{ new_name.stdout }}" 
   - name: show variable value
     debug:
       msg: "{{ new_name.stdout_lines }}"
   - mysql_db:
       login_host: 3.10.23.100
       login_user: root
       login_password: Miami@2019
       name: "{{ db_name }}"
       state: present
   - mysql_user:
       login_host: 3.10.23.100
       login_user: root
       login_password: Miami@2019
       name: "{{ var_name }}"
       password: 12345
       #name: "{{ new_name.stdout_lines }}"
       #password: 12345
       priv: '{{ db_name }}.*:ALL'
       host: '%'
       state: present 
