---
# tasks file for apache

#- name: service start 
#  service:
#     name: httpd
#     state: stopped
#- name: run shell Script on remote host
#  script: /root/script/script.sh
 # register: output_log
 # ignore_errors: yes

#- name: copy the output to a local file
#  copy:
 #   content: "{{ output_log.stdout }}"
  #  dest: "/tmp/log.txt"
  #delegate_to: localhost

  #args:
   #executable: /bin/bash
   #chdir: /var/log/httpd/
#- name: sleep for 15 seconds and continue with play
#  wait_for:
#    timeout: 1
- name: verify httpd-server is listening on 80
  wait_for: port=80 delay=5  timeout=10 
  #msg: "Timeout waiting for 80 to respond"
  ignore_errors: yes
  register: port_check

#- name: Try to restart httpd if not started
 # service: name=httpd state=restarted
  #when: port_check.failed == true

#- debug:
 #  var: telout1

- name: Gathering service facts
  service_facts:
  register: output1

- debug: 
   msg: output1 {{ ansible_facts.services["httpd.service"].state }}
  register: output

#- debug:
 #  var: output


#- debug:
 #  msg: "httpd is not running"
 # when: "output.find('v=' ~ unknown) == -1"
 # notify: restart httpd

#- name: get error log
#  service: name=httpd state=restarted
#  script: /root/script/script.sh
#  register: output_log
#  ignore_errors: yes
#  copy:  content= "{{ output_log.stdout }}" dest= "/tmp/log.txt"
#  delegate_to: localhost
- import_tasks: tasks/sometasks.yml
  #notify: restart httpd
  #when: output.msg == 'output1 unknown'
  when: output.msg == 'output1 unknown' or  port_check.failed == true

