---
- name: run shell Script on remote host
  script: /etc/ansible/apache/tasks/script.sh
  register: output_log
  ignore_errors: yes
#
- name: copy the output to a local file
  copy:
   content: "{{ output_log.stdout }}"
   dest: "/tmp/log.txt"
  delegate_to: localhost
 
- name: Try to restart httpd 
  service: name=httpd state=restarted
 
- wait_for:
    timeout: 5
# Validating the Servcie Again

- name: check httpd service facts
  service_facts:
  register: check

- debug:
   msg: check {{ ansible_facts.services["httpd.service"].state }}
  register: output2


- local_action: shell echo "service restarted by ansibile" >> /tmp/msg1.txt
  #notify: restart httpd
  when: output2.msg == 'check running'
#
